### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'IoU' (for AB3DMOT)

### ISSUE THREAD

**Issue by MaxBial** [avstack-lab/lib-avstack-core#22]
```
File ~/AVstack/carla_sandbox/carla-sandbox/submodules/lib-avstack-core/avstack/modules/assignment.py:43, in build_A_from_iou(boxes1, boxes2, **kwargs)
     41         except AttributeError:
     42             pass
---> 43         iou = b1.IoU(b2, **kwargs)
     44         A[i, j] = -iou
     45 return A

AttributeError: 'dict' object has no attribute 'IoU'
```

Based on the "Readthedocs" "Track Objects" --> when switching from "BasicBoxTracker3D" to "Ab3dmotTracker" and executing the following code:
```

# detection and tracking
ego_ref = DM.get_ego(frame=0).as_reference()
for frame in tqdm(DM.frames):
    pc = DM.get_lidar(frame, sensor='main_lidar')
    timestamp = DM.framerate * frame
    
    # -- perception
    dets = P(pc, frame=frame, identifier='lidar-detections')
    
    # -- tracking
    tracks = T(detections=dets, t=timestamp, frame=frame, platform=ego_ref)
```

then this AttributeError above occurs.

Could you please check this?

PS: I placed the issue here in avstack-core, due to the fact that the root of the issue lies here, eventhough I am facing this while using the carla-sandbox.

Thanks

**Comment by roshambo919** [comment]
Fixed by updating carla sandbox submodules to latest. https://github.com/avstack-lab/carla-sandbox/tree/cf541cdf76ef5399a82d84643f77be97647c31d5
