### ISSUE TITLE
'MMDetObjectDetector3D' object has no attribute 'save_folder'

### ISSUE THREAD

**Issue by ronyshaji** [avstack-lab/lib-avstack-core#30]
Hello

I was trying the tracking example in the documentation and stuck with an error.
While running the below code snippet, I am getting an error

```
# %%capture
# ^^ suppress output
percep_res_frames, percep_res_seq, _ = avapi.evaluation.get_percep_results_from_folder(
    DM, P.save_folder, sensor_eval='main_lidar', multiprocess=True)
track_res_frames, track_res_seq, track_res_exp = avapi.evaluation.get_track_results_from_folder(
    DM, T.save_folder, sensor_eval='main_lidar', multiprocess=False)
```
The error came as:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 4
      1 # %%capture
      2 # ^^ suppress output
      3 percep_res_frames, percep_res_seq, _ = avapi.evaluation.get_percep_results_from_folder(
----> 4     DM, P.save_folder, sensor_eval='main_lidar', multiprocess=True)
      5 track_res_frames, track_res_seq, track_res_exp = avapi.evaluation.get_track_results_from_folder(
      6     DM, T.save_folder, sensor_eval='main_lidar', multiprocess=False)

AttributeError: 'MMDetObjectDetector3D' object has no attribute 'save_folder'
```

I checked the MMDetObjectDetector3D class and its parent classes and can't able to find out the usage of the save_folder.
Do we need to create the folder our self? What data will be saved in that folder?

Thanks for the feedback

**Comment by roshambo919** [comment]
Thanks for pointing this out. I'm in the middle of a big update to the code
base and I'll revisit the tutorials once that is completed. Hopefully this
weekend.

**Comment by ronyshaji** [comment]
Great. Thanks for the update.

**Comment by ronyshaji** [comment]
Hello @roshambo919, I hope you're doing well. I was wondering if there have been any developments regarding the issue mentioned earlier?

**Comment by roshambo919** [comment]
So sorry for the delay. I just now merged in some updates to the `main` branch. The biggest changes are the incorporation of config-based building of modules. In general, looking at the `tests` folder is the best way to see AVstack working in action. The tests are required to pass before I merge anything in, so they should always work if things are set up properly. The documentation online is out of date - I will have a student work on fixing that.

I'm targeting an official release of a v0.1 AVstack on pypi at around April 1, FYI. 

In the meantime, if you want support for a particular use case of AVstack, feel free to point me to your git repository and I can provide some support.

**Comment by ronyshaji** [comment]
@roshambo919 Thanks for the feedback. I have updated the sub-modules based on your change, but unfortunately I was not able to rectify the error. The error says that the below object 'P' does not have an attribute which used in the next stage (evaluation)
```
P = avstack.modules.perception.object3d.MMDetObjectDetector3D(
        model='pointpillars', dataset='kitti', threshold=0.7, 
        save_output=True, save_folder=result_folder)
```
Here the folder which the results should be saves is passed as an argument, which is an attribute of P. But unfortunately P does not have any attribute like save_folder (P.save_folder).

```
percep_res_frames, percep_res_seq, _ = avapi.evaluation.get_percep_results_from_folder(
    DM, P.save_folder, sensor_eval='main_lidar', multiprocess=True)
```
I checked the MMDetObjectDetector3D class and can't find anything related to save_folder or something. So there is no folder available and the evaluation can't be performed. I am still new to the AVstack and primarily trying out based on the tutorial available on the website.

Thanks
Rony Shaji

**Comment by roshambo919** [comment]
Yes, I removed the `save_folder` input argument completely. Your code should now just be:
```
P = avstack.modules.perception.object3d.MMDetObjectDetector3D(
        model='pointpillars', dataset='kitti', threshold=0.7
) 
```
If you need to save the output, consider saving it manually for now or using a logging hook as in https://github.com/avstack-lab/lib-avstack-core/blob/b9d16713b35cf8f2f1cbe78924025b72ad578767/tests/utils/test_logger.py#L50

I'll try to get a logging example working again soon.

**Comment by ronyshaji** [comment]
Hey @roshambo919 

Hope you are doing fine. I am still trying out the AVstack and wondering whether the v0.1 AVstack is already out. As mentioned I faced some issues with the current version, and hopefully it will be solved with the new version.

Also I created a custom map of a test field in CARLA and is planning to do multi object tracking using infrastructural sensor(LIDAR) and would like to know whether I can incorporate AVstack there? I saw the tutorial to Generate Collaborative CARLA Dataset, but the methods are not much clear. So your feedback will be greatly appreciated.

**Comment by roshambo919** [comment]
Hi @ronyshaji - thanks so much for following up. There's a lot of progress going on with the carla integration including the development of [`lib-avstack-carla`](https://github.com/avstack-lab/lib-avstack-carla) and the in-progress integration with the [`carla-sandbox`](https://github.com/carla-sandbox).

Once I finish up a project this week, I'll write a tutorial for how to use it. I think you'll find it very useful.

**Comment by ronyshaji** [comment]
@roshambo919 Thanks for the feedback. Hope the tutorials will cover infrastructure sensor based tracking too 🙂

**Comment by roshambo919** [comment]
@ronyshaji I patched the docs through the tracking example in a branch named "update". This includes basic perception and tracking examples. Infrastructure examples to come in the future.

https://github.com/avstack-lab/avstack-docs/tree/update

**Comment by ronyshaji** [comment]
Hey @roshambo919 

Thanks for the update. 
Unfortunately I am still facing some issues. First of all, I think the CARLA dataset download link in the .sh is not working.
I tried to download manually still it is not working [https://download_carla_datasets.sh/](https://github.com/avstack-lab/lib-avstack-api/blob/4466383681bab66c5da6358c07913b4f5716fe34/data/download_CARLA_datasets.sh#L12). KITTI and nuScenes are working as intended. Since my main concentration is CARLA, it would be great if you provide a working link to download it.

Also got an error with line 6 in [base.py](https://github.com/avstack-lab/lib-avstack-api/blob/4466383681bab66c5da6358c07913b4f5716fe34/avapi/visualize/base.py), I had to replace 
`lidar_cmap = plt.cm.get_cmap("hsv", 256)`  

by 

`lidar_cmap = plt.get_cmap("hsv", 256)`

Regards
Rony Shaji
