### ISSUE TITLE
AttributeError: 'ObjectState' object has no attribute 'format_as_string'

### ISSUE THREAD

**Issue by MaxBial** [avstack-lab/lib-avstack-core#9]
File ~/AVstack/carla_sandbox/carla-sandbox/submodules/lib-avstack-core/avstack/modules/tracking/base.py:134, in <listcomp>(.0)
    132 tracks = self.track(t, frame, detections, **kwargs)
    133 if self.save:
--> 134     trk_str = "\n".join([trk.format_as_string() for trk in tracks])
    135     fname = os.path.join(self.save_folder, "%06d.txt" % self.frame)
    136     with open(fname, "w") as f:

AttributeError: 'ObjectState' object has no attribute 'format_as_string'

Based on the "Readthedocs" "Track Objects"  --> when switching from "BasicBoxTracker3D" to "Ab3dmotTracker" then this AttributeError above occurs. 

Could you please check this?

Thanks

**Comment by roshambo919** [comment]
Yes absolutely. I'm in the process of updating the `carla-sandbox` submodules to their newest versions, and I believe I've left them in a broken state. I'll have this fixed by the end of the week.

**Comment by MaxBial** [comment]
Short addition. 
Also this file is missing or it was renamed in your substantial changes: "hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth"

I hope those comments/hints will help you.

Best Regards

**Comment by roshambo919** [comment]
Thanks for the feedback. I was able to fix a few things and confirmed that the following code ran on my end with the latest repo.

Other notable changes: I changed the poetry dependencies base on python3.9 and I added a new submodule. Hopefully this isn't a problem for you.

The perception evaluation does not seem to have the correct output, but the tracking evaluation does, so I'll push this up and figure the percep eval later.

```
import os
import avstack
import avapi
from tqdm import tqdm

%load_ext autoreload
%autoreload 2

data_base = '/data/spencer/'
obj_data_dir_k = os.path.join(data_base, 'KITTI/object')
raw_data_dir_k = os.path.join(data_base, 'KITTI/raw')
obj_data_dir_c = os.path.join(data_base, 'CARLA/carla-object-v1')

KSM = avapi.kitti.KittiScenesManager(obj_data_dir_k, raw_data_dir_k, convert_raw=False)
KDM = KSM.get_scene_dataset_by_index(scene_idx=0)

DM = KDM  # let's use kitti for this one

result_folder = 'results_lidar'
P = avstack.modules.perception.object3d.MMDetObjectDetector3D(
        model='pointpillars', dataset='kitti', threshold=0.7, 
        save_output=True, save_folder=result_folder)
T = avstack.modules.tracking.tracker3d.BasicBoxTracker3D(
        framerate=DM.framerate, save_output=True, save_folder=result_folder)

# detection and tracking
ego_ref = DM.get_ego(frame=0).as_reference()
for frame in tqdm(DM.frames):
    pc = DM.get_lidar(frame, sensor='main_lidar')
    timestamp = DM.framerate * frame
    
    # -- perception
    dets = P(pc, frame=frame, identifier='lidar-detections')
    
    # -- tracking
    tracks = T(detections=dets, t=timestamp, frame=frame, platform=ego_ref)

# %%capture
# ^^ suppress output
percep_res_frames, percep_res_seq, _ = avapi.evaluation.get_percep_results_from_folder(
    DM, P.save_folder, sensor_eval='main_lidar', multiprocess=True)
track_res_frames, track_res_seq, track_res_exp = avapi.evaluation.get_track_results_from_folder(
    DM, T.save_folder, sensor_eval='main_lidar', multiprocess=True)

print('Aggregate perception results:\n', percep_res_seq, '\n')
print('Aggregate tracking results:\n', track_res_seq, '\n')
print('Expanded track metrics include:\n', track_res_exp.keys(), '\n')
print(f'     e.g., HOTA_LocA(0): {track_res_exp["HOTA_LocA(0)"]}')

```
